#!/bin/bash

echo "🔧 Fixing dependency issues in GitHub location..."
echo ""

TARGET_DIR="/Users/eliah/Documents/GitHub/Lancet/LancetHubCurrentBackup"

echo "📋 Instructions to fix the caniuse-lite issue:"
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "cd $TARGET_DIR"
echo ""
echo "# Option 1: Try installing caniuse-lite directly"
echo "npm install caniuse-lite@latest"
echo ""
echo "# If that doesn't work, try Option 2: Clean reinstall"
echo "rm -rf node_modules package-lock.json"
echo "npm cache clean --force"
echo "npm install"
echo ""
echo "# If you still have issues, try Option 3: Update browserslist"
echo "npx browserslist@latest --update-db"
echo "npm install caniuse-lite browserslist"
echo ""
echo "# Then start the server"
echo "npm run dev"
echo ""
echo "💡 Note: This is a common issue with Next.js when dependencies get out of sync."