# Netlify configuration file
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Headers for better security and cookie handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Function configuration for Next.js
[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variable hints (actual values should be set in Netlify dashboard)
# NEXTAUTH_URL = "https://your-site.netlify.app"
# NEXTAUTH_SECRET = "your-32-character-secret-key"
# NODE_ENV = "production"
EOF < /dev/null