[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Set Node version - matching .nvmrc
  NODE_VERSION = "18.19.0"
  # Increase timeout for build
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  # Next.js specific settings
  NEXT_TELEMETRY_DISABLED = "1"
  # Disable SSG/ISR tracing that might load Airtable at build time
  NETLIFY_SKIP_FUNCTIONS_CACHE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Prevent aggressive bundling that causes build-time module loading
  node_bundler = "zisi"
  included_files = ["node_modules/**"]

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect from Netlify URL to custom domain (if applicable)
[[redirects]]
  from = "https://pancemic-resilience-hub.netlify.app/*"
  to = "https://pandemic-resilience-hub.org/:splat"
  status = 301
  force = true

# API routes and image optimization are handled automatically by @netlify/plugin-nextjs

# Environment-specific build settings
[context.production.environment]
  # Use real Airtable data
  USE_MOCK_DATA = "false"

[context.deploy-preview.environment]
  USE_MOCK_DATA = "false"

[context.branch-deploy.environment]
  USE_MOCK_DATA = "false"