[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Set Node version
  NODE_VERSION = "18"
  # Increase timeout for build
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect from Netlify URL to custom domain (if applicable)
[[redirects]]
  from = "https://pancemic-resilience-hub.netlify.app/*"
  to = "https://pandemic-resilience-hub.org/:splat"
  status = 301
  force = true

# API routes and image optimization are handled automatically by @netlify/plugin-nextjs

# Environment-specific build settings
[context.production.environment]
  # Use real Airtable data
  USE_MOCK_DATA = "false"

[context.deploy-preview.environment]
  USE_MOCK_DATA = "false"

[context.branch-deploy.environment]
  USE_MOCK_DATA = "false"