import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

// Helper function to get fallback bibliography data
function getFallbackBibliography() {
  return [
    // Dimension 1: Environmental Stewardship & Resource Security
    {
      id: 'bib-1',
      Name: 'Preventing the next pandemic: Zoonotic diseases and how to break the chain of transmission',
      Authors: 'Daszak, P, et al.',
      Publication: 'UNEP and ILRI',
      Year: '2020',
      Type: 'Report',
      Keywords: 'zoonotic diseases, pandemic prevention, environmental health, transmission',
      Abstract: 'Comprehensive analysis of zoonotic disease transmission and prevention strategies.',
      Field: 'Environmental Health',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-2',
      Name: 'Workshop Report on Biodiversity and Pandemics',
      Authors: 'IPBES',
      Publication: 'Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services',
      Year: '2020',
      Type: 'Report',
      Keywords: 'biodiversity, pandemics, ecosystem services, policy',
      Abstract: 'Expert assessment of the relationships between biodiversity and pandemic emergence.',
      Field: 'Environmental Policy',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-3',
      Name: 'A safe operating space for humanity',
      Authors: 'Rockström, J, et al.',
      Publication: 'Nature',
      Year: '2009',
      Volume: '461',
      Pages: '472-475',
      Type: 'Research Article',
      Keywords: 'planetary boundaries, sustainability, earth system, environmental limits',
      Abstract: 'Identification of nine planetary boundaries within which humanity can operate safely.',
      Field: 'Earth System Science',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-4',
      Name: 'Ecology and economics for pandemic prevention',
      Authors: 'Dobson, A. P, et al.',
      Publication: 'Science',
      Year: '2020',
      Volume: '369',
      Issue: '6502',
      Pages: '379-381',
      Type: 'Research Article',
      Keywords: 'pandemic prevention, ecology, economics, cost-benefit analysis',
      Abstract: 'Economic analysis of ecological interventions for pandemic prevention.',
      Field: 'Environmental Economics',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-5',
      Name: 'Making Peace with Nature: A scientific blueprint to tackle the climate, biodiversity and pollution emergencies',
      Authors: 'UNEP',
      Publication: 'United Nations Environment Programme',
      Year: '2021',
      Type: 'Report',
      Keywords: 'climate change, biodiversity, pollution, environmental crises',
      Abstract: 'Comprehensive blueprint for addressing interconnected environmental emergencies.',
      Field: 'Environmental Policy',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-6',
      Name: 'Safeguarding human health in the Anthropocene epoch',
      Authors: 'Whitmee, S, et al.',
      Publication: 'The Lancet',
      Year: '2015',
      Volume: '386',
      Pages: '1973-2028',
      Type: 'Commission Report',
      Keywords: 'planetary health, Anthropocene, human health, environmental change',
      Abstract: 'Lancet Commission report on the health implications of environmental change in the Anthropocene.',
      Field: 'Planetary Health',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-7',
      Name: 'Species diversity and disease risk',
      Authors: 'Ostfeld, R. S., & Keesing, F.',
      Publication: 'Annual Review of Ecology, Evolution, and Systematics',
      Year: '2020',
      Volume: '51',
      Pages: '399-419',
      Type: 'Review',
      Keywords: 'biodiversity, disease risk, dilution effect, zoonoses',
      Abstract: 'Review of relationships between species diversity and infectious disease risk.',
      Field: 'Disease Ecology',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-8',
      Name: 'Unhealthy Landscapes: Policy recommendations on land use change and infectious disease emergence',
      Authors: 'Patz, J. A, et al.',
      Publication: 'Environmental Health Perspectives',
      Year: '2004',
      Volume: '112',
      Issue: '10',
      Pages: '1092-1098',
      Type: 'Research Article',
      Keywords: 'land use change, infectious disease, policy, environmental health',
      Abstract: 'Policy recommendations for managing land use to reduce disease emergence.',
      Field: 'Environmental Health',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-9',
      Name: 'Connecting global priorities: biodiversity and human health',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2018',
      Type: 'Report',
      Keywords: 'biodiversity, human health, One Health, global priorities',
      Abstract: 'WHO report on the interconnections between biodiversity and human health.',
      Field: 'Global Health',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    {
      id: 'bib-10',
      Name: 'Land use-induced spillover: priority actions for prevention',
      Authors: 'Plowright, R. K, et al.',
      Publication: 'Science Advances',
      Year: '2021',
      Volume: '7',
      Issue: '37',
      Pages: 'eabl4183',
      Type: 'Research Article',
      Keywords: 'spillover, land use, prevention, zoonotic disease',
      Abstract: 'Priority actions for preventing pathogen spillover through land use management.',
      Field: 'Disease Ecology',
      Dimension: 'Environmental Stewardship & Resource Security'
    },
    // Dimension 2: Social Equity & Well-being
    {
      id: 'bib-11',
      Name: 'The Health Gap: The Challenge of an Unequal World',
      Authors: 'Marmot, M.',
      Publication: 'Bloomsbury Publishing',
      Year: '2015',
      Type: 'Book',
      Keywords: 'health inequalities, social determinants, health equity, global health',
      Abstract: 'Comprehensive examination of health inequalities and their social determinants.',
      Field: 'Social Epidemiology',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-12',
      Name: 'The Spirit Level: Why Equality is Better for Everyone',
      Authors: 'Wilkinson, R. & Pickett, K.',
      Publication: 'Penguin Books',
      Year: '2009',
      Type: 'Book',
      Keywords: 'inequality, social outcomes, public health, social cohesion',
      Abstract: 'Analysis of how income inequality affects social and health outcomes.',
      Field: 'Social Policy',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-13',
      Name: 'Pathologies of Power: Health, Human Rights, and the New War on the Poor',
      Authors: 'Farmer, P.',
      Publication: 'University of California Press',
      Year: '2005',
      Type: 'Book',
      Keywords: 'human rights, health equity, structural violence, poverty',
      Abstract: 'Examination of structural violence and its impact on health and human rights.',
      Field: 'Medical Anthropology',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-14',
      Name: 'Global health 2035: a world converging within a generation',
      Authors: 'Lancet Commission on Global Health 2035',
      Publication: 'The Lancet',
      Year: '2013',
      Volume: '382',
      Pages: '1898-1955',
      Type: 'Commission Report',
      Keywords: 'global health, health convergence, investment, development',
      Abstract: 'Lancet Commission report on achieving global health convergence by 2035.',
      Field: 'Global Health',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-15',
      Name: 'Social conditions as fundamental causes of health inequalities',
      Authors: 'Phelan, J, et al.',
      Publication: 'Journal of Health and Social Behavior',
      Year: '2010',
      Volume: '51',
      Issue: 'Suppl',
      Pages: 'S28-S40',
      Type: 'Research Article',
      Keywords: 'health inequalities, social conditions, fundamental causes, social determinants',
      Abstract: 'Theory of social conditions as fundamental causes of health inequalities.',
      Field: 'Medical Sociology',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-16',
      Name: 'Communities in Action: Pathways to Health Equity',
      Authors: 'National Academies of Sciences, Engineering, and Medicine',
      Publication: 'National Academies Press',
      Year: '2017',
      Type: 'Report',
      Keywords: 'health equity, community action, social determinants, interventions',
      Abstract: 'Evidence-based pathways for communities to advance health equity.',
      Field: 'Public Health',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-17',
      Name: 'The COVID-19 pandemic and health inequalities',
      Authors: 'Bambra, C, et al.',
      Publication: 'Journal of Epidemiology & Community Health',
      Year: '2020',
      Volume: '74',
      Issue: '11',
      Pages: '964-968',
      Type: 'Research Article',
      Keywords: 'COVID-19, health inequalities, pandemic, social determinants',
      Abstract: 'Analysis of how COVID-19 has exacerbated existing health inequalities.',
      Field: 'Social Epidemiology',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-18',
      Name: 'Closing the Gap in a Generation',
      Authors: 'WHO Commission on Social Determinants of Health',
      Publication: 'WHO',
      Year: '2008',
      Type: 'Report',
      Keywords: 'social determinants, health equity, WHO, global health',
      Abstract: 'WHO Commission report on achieving health equity through action on social determinants.',
      Field: 'Global Health Policy',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-19',
      Name: 'COVID-19 and African Americans',
      Authors: 'Yancy, C. W.',
      Publication: 'JAMA',
      Year: '2020',
      Volume: '323',
      Issue: '19',
      Pages: '1891-1892',
      Type: 'Commentary',
      Keywords: 'COVID-19, racial disparities, African Americans, health equity',
      Abstract: 'Commentary on the disproportionate impact of COVID-19 on African Americans.',
      Field: 'Health Disparities',
      Dimension: 'Social Equity & Well-being'
    },
    {
      id: 'bib-20',
      Name: 'The association between income and life expectancy in the United States, 2001-2014',
      Authors: 'Chetty, R, et al.',
      Publication: 'JAMA',
      Year: '2016',
      Volume: '315',
      Issue: '16',
      Pages: '1750-1766',
      Type: 'Research Article',
      Keywords: 'income inequality, life expectancy, health disparities, mortality',
      Abstract: 'Analysis of the relationship between income and life expectancy across US regions.',
      Field: 'Health Economics',
      Dimension: 'Social Equity & Well-being'
    },
    // Dimension 3: Healthcare System Capacity & Integration
    {
      id: 'bib-21',
      Name: 'Primary health care: realizing the vision',
      Authors: 'Ghebreyesus, TA',
      Publication: 'Bulletin of the World Health Organization',
      Year: '2018',
      Volume: '96',
      Issue: '10',
      Pages: '668-668A',
      Type: 'Editorial',
      Keywords: 'primary health care, universal health coverage, health systems',
      Abstract: 'Vision for achieving primary health care as foundation of universal health coverage.',
      Field: 'Health Systems',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-22',
      Name: 'A framework for health system resilience in the context of health emergencies',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2021',
      Type: 'Framework',
      Keywords: 'health system resilience, emergency preparedness, health systems strengthening',
      Abstract: 'WHO framework for building resilient health systems in emergency contexts.',
      Field: 'Health Systems',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-23',
      Name: 'National Health Security Preparedness Index',
      Authors: 'NHSPI',
      Publication: 'National Health Security Preparedness Index',
      Year: '2024',
      Type: 'Index Report',
      Keywords: 'health security, preparedness, measurement, indicators',
      Abstract: 'Annual assessment of US health security preparedness capabilities.',
      Field: 'Health Security',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-24',
      Name: 'Crisis standards of care: a systems framework for catastrophic disaster response',
      Authors: 'Institute of Medicine',
      Publication: 'National Academies Press',
      Year: '2012',
      Type: 'Report',
      Keywords: 'crisis standards, disaster response, healthcare surge, ethics',
      Abstract: 'Framework for healthcare system response during catastrophic disasters.',
      Field: 'Emergency Medicine',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-25',
      Name: 'The Federal Medical Station Program',
      Authors: 'CDC',
      Publication: 'Centers for Disease Control and Prevention',
      Year: '2023',
      Type: 'Program Overview',
      Keywords: 'surge capacity, medical stations, emergency response, healthcare',
      Abstract: 'CDC program for rapidly deployable medical surge capacity.',
      Field: 'Emergency Preparedness',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-26',
      Name: 'Operational Readiness Review: A Toolkit for the Healthcare System',
      Authors: 'ASPR',
      Publication: 'HHS Office of the Assistant Secretary for Preparedness and Response',
      Year: '2022',
      Type: 'Toolkit',
      Keywords: 'operational readiness, healthcare preparedness, assessment tools',
      Abstract: 'Toolkit for assessing healthcare system operational readiness.',
      Field: 'Healthcare Preparedness',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-27',
      Name: 'Lessons from the COVID-19 pandemic for US health care systems',
      Authors: 'Blumenthal, D, et al.',
      Publication: 'New England Journal of Medicine',
      Year: '2020',
      Volume: '383',
      Pages: '1488-1491',
      Type: 'Perspective',
      Keywords: 'COVID-19, health systems, lessons learned, pandemic response',
      Abstract: 'Key lessons for US healthcare systems from COVID-19 experience.',
      Field: 'Health Policy',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-28',
      Name: 'Surge capacity: a review of the history, applications, and lessons learned',
      Authors: 'Hick, JL, et al.',
      Publication: 'Disaster Medicine and Public Health Preparedness',
      Year: '2020',
      Volume: '14',
      Issue: '4',
      Pages: '403-412',
      Type: 'Review',
      Keywords: 'surge capacity, disaster medicine, healthcare systems, emergency response',
      Abstract: 'Comprehensive review of healthcare surge capacity concepts and applications.',
      Field: 'Disaster Medicine',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-29',
      Name: 'Building health system resilience through policy development',
      Authors: 'Thomas, S, et al.',
      Publication: 'The Lancet Global Health',
      Year: '2023',
      Volume: '11',
      Issue: '9',
      Pages: 'e1454-e1458',
      Type: 'Policy Analysis',
      Keywords: 'health system resilience, policy development, systems strengthening',
      Abstract: 'Policy approaches for building resilient health systems.',
      Field: 'Health Policy',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-30',
      Name: 'Digital health and COVID-19',
      Authors: 'Budd, J, et al.',
      Publication: 'Nature Medicine',
      Year: '2020',
      Volume: '26',
      Issue: '8',
      Pages: '1183-1192',
      Type: 'Review',
      Keywords: 'digital health, COVID-19, telehealth, health technology',
      Abstract: 'Role of digital health technologies in pandemic response.',
      Field: 'Digital Health',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    // Dimension 4: Economic Stability & Crisis Protection
    {
      id: 'bib-31',
      Name: 'The Great Influenza: Economic Effects of the 1918 Pandemic',
      Authors: 'Garrett, TA',
      Publication: 'Federal Reserve Bank of St. Louis',
      Year: '2007',
      Type: 'Economic Analysis',
      Keywords: '1918 pandemic, economic impact, historical analysis, public health',
      Abstract: 'Economic analysis of the 1918 influenza pandemic impacts.',
      Field: 'Economic History',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-32',
      Name: 'The Economics of Pandemic Preparedness',
      Authors: 'Jamison, DT, et al.',
      Publication: 'Finance & Development',
      Year: '2018',
      Volume: '55',
      Issue: '2',
      Pages: '14-17',
      Type: 'Economic Analysis',
      Keywords: 'pandemic economics, preparedness costs, economic resilience',
      Abstract: 'Economic case for investing in pandemic preparedness.',
      Field: 'Health Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-33',
      Name: 'COVID-19 and the US economy: FAQ',
      Authors: 'Congressional Research Service',
      Publication: 'CRS',
      Year: '2021',
      Type: 'Report',
      Keywords: 'COVID-19, economic impact, US economy, policy response',
      Abstract: 'Analysis of COVID-19 economic impacts and policy responses.',
      Field: 'Economic Policy',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-34',
      Name: 'Building financial resilience through financial and digital literacy',
      Authors: 'OECD',
      Publication: 'OECD Publishing',
      Year: '2022',
      Type: 'Report',
      Keywords: 'financial resilience, digital literacy, economic security',
      Abstract: 'OECD report on building economic resilience through literacy.',
      Field: 'Financial Policy',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-35',
      Name: 'The economic impact of the COVID-19 pandemic on radiology practices',
      Authors: 'Norbash, AM, et al.',
      Publication: 'Radiology',
      Year: '2020',
      Volume: '296',
      Issue: '3',
      Pages: 'E141-E144',
      Type: 'Research Article',
      Keywords: 'COVID-19, economic impact, healthcare sector, radiology',
      Abstract: 'Analysis of pandemic economic impacts on healthcare practices.',
      Field: 'Healthcare Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-36',
      Name: 'Small business survival capabilities and pandemic planning',
      Authors: 'Runyan, RC',
      Publication: 'Disaster Prevention and Management',
      Year: '2006',
      Volume: '15',
      Issue: '5',
      Pages: '543-555',
      Type: 'Research Article',
      Keywords: 'small business, disaster resilience, pandemic planning, economic survival',
      Abstract: 'Framework for small business pandemic preparedness and survival.',
      Field: 'Business Continuity',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-37',
      Name: 'Economic preparedness for public health emergencies',
      Authors: 'Fan, VY, et al.',
      Publication: 'Health Security',
      Year: '2018',
      Volume: '16',
      Issue: '1',
      Pages: 'S119-S127',
      Type: 'Policy Analysis',
      Keywords: 'economic preparedness, public health emergencies, financing',
      Abstract: 'Framework for economic preparedness in health emergencies.',
      Field: 'Health Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-38',
      Name: 'The role of social protection in building resilience to shocks',
      Authors: 'World Bank',
      Publication: 'World Bank Group',
      Year: '2020',
      Type: 'Report',
      Keywords: 'social protection, economic resilience, crisis response, safety nets',
      Abstract: 'World Bank analysis of social protection systems in crisis resilience.',
      Field: 'Development Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-39',
      Name: 'Pandemic risk insurance: lessons from the COVID-19 crisis',
      Authors: 'Richter, A & Wilson, TC',
      Publication: 'Risk Management and Insurance Review',
      Year: '2020',
      Volume: '23',
      Issue: '4',
      Pages: '361-377',
      Type: 'Research Article',
      Keywords: 'pandemic insurance, risk management, COVID-19, economic protection',
      Abstract: 'Analysis of pandemic risk insurance mechanisms and lessons learned.',
      Field: 'Risk Management',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-40',
      Name: 'Essential workers and pandemic resilience',
      Authors: 'McNicholas, C & Poydock, M',
      Publication: 'Economic Policy Institute',
      Year: '2020',
      Type: 'Policy Brief',
      Keywords: 'essential workers, economic security, pandemic response, labor policy',
      Abstract: 'Analysis of essential worker protections and economic security.',
      Field: 'Labor Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    // Dimension 5: Governance Coordination & Community Leadership
    {
      id: 'bib-41',
      Name: 'Leadership in a crisis: responding to the coronavirus outbreak',
      Authors: 'D'Auria, G & De Smet, A',
      Publication: 'McKinsey & Company',
      Year: '2020',
      Type: 'Analysis',
      Keywords: 'crisis leadership, COVID-19, governance, decision-making',
      Abstract: 'Framework for effective leadership during crisis situations.',
      Field: 'Leadership Studies',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-42',
      Name: 'Global governance for health',
      Authors: 'Kickbusch, I, et al.',
      Publication: 'The Lancet',
      Year: '2013',
      Volume: '381',
      Issue: '9874',
      Pages: '1859-1869',
      Type: 'Series',
      Keywords: 'global governance, health diplomacy, international cooperation',
      Abstract: 'Analysis of global governance mechanisms for health challenges.',
      Field: 'Global Health Governance',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-43',
      Name: 'National Incident Management System',
      Authors: 'FEMA',
      Publication: 'Federal Emergency Management Agency',
      Year: '2017',
      Type: 'Framework',
      Keywords: 'incident management, emergency response, coordination, governance',
      Abstract: 'National framework for coordinated emergency response.',
      Field: 'Emergency Management',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-44',
      Name: 'Whole-of-society pandemic readiness',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2009',
      Type: 'Guidance',
      Keywords: 'pandemic readiness, whole-of-society, governance, coordination',
      Abstract: 'WHO guidance on whole-of-society approaches to pandemic preparedness.',
      Field: 'Pandemic Preparedness',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-45',
      Name: 'Building adaptive capacity through policy and practice',
      Authors: 'Fazey, I, et al.',
      Publication: 'Environmental Science & Policy',
      Year: '2018',
      Volume: '79',
      Pages: '1-8',
      Type: 'Research Article',
      Keywords: 'adaptive capacity, governance, policy integration, resilience',
      Abstract: 'Framework for building adaptive capacity through governance.',
      Field: 'Environmental Governance',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-46',
      Name: 'Community Preparedness and Response',
      Authors: 'Ready.gov',
      Publication: 'Department of Homeland Security',
      Year: '2024',
      Type: 'Resource',
      Keywords: 'community preparedness, citizen engagement, emergency planning',
      Abstract: 'Resources for community-level emergency preparedness.',
      Field: 'Community Preparedness',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-47',
      Name: 'From panic and neglect to investing in health security',
      Authors: 'Sands, P, et al.',
      Publication: 'The Lancet',
      Year: '2016',
      Volume: '387',
      Issue: '10033',
      Pages: '2196-2214',
      Type: 'Commission Report',
      Keywords: 'health security, governance, financing, global cooperation',
      Abstract: 'Commission report on governance and financing for health security.',
      Field: 'Global Health Security',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-48',
      Name: 'Collaborative governance in theory and practice',
      Authors: 'Ansell, C & Gash, A',
      Publication: 'Journal of Public Administration Research and Theory',
      Year: '2008',
      Volume: '18',
      Issue: '4',
      Pages: '543-571',
      Type: 'Research Article',
      Keywords: 'collaborative governance, public administration, stakeholder engagement',
      Abstract: 'Theoretical framework for collaborative governance approaches.',
      Field: 'Public Administration',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-49',
      Name: 'Emergency management: principles and practice for local government',
      Authors: 'Waugh, WL & Tierney, K',
      Publication: 'ICMA Press',
      Year: '2007',
      Type: 'Book',
      Keywords: 'emergency management, local government, leadership, coordination',
      Abstract: 'Comprehensive guide for local government emergency management.',
      Field: 'Emergency Management',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-50',
      Name: 'National Biodefense Strategy',
      Authors: 'White House',
      Publication: 'Executive Office of the President',
      Year: '2018',
      Type: 'Strategy Document',
      Keywords: 'biodefense, national security, governance, coordination',
      Abstract: 'National strategy for biodefense coordination and implementation.',
      Field: 'National Security',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    // Dimension 6: Information Infrastructure & Communication
    {
      id: 'bib-51',
      Name: 'Managing the COVID-19 infodemic',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2020',
      Type: 'Report',
      Keywords: 'infodemic, misinformation, health communication, social media',
      Abstract: 'WHO framework for managing information during health emergencies.',
      Field: 'Health Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-52',
      Name: 'Crisis and Emergency Risk Communication',
      Authors: 'CDC',
      Publication: 'Centers for Disease Control and Prevention',
      Year: '2019',
      Type: 'Manual',
      Keywords: 'crisis communication, risk communication, emergency response, public health',
      Abstract: 'CDC manual for effective crisis and emergency risk communication.',
      Field: 'Risk Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-53',
      Name: 'The role of digital technologies in COVID-19 surveillance and control',
      Authors: 'Wang, CJ, et al.',
      Publication: 'JAMA',
      Year: '2020',
      Volume: '324',
      Issue: '14',
      Pages: '1416-1417',
      Type: 'Viewpoint',
      Keywords: 'digital health, surveillance, COVID-19, technology, privacy',
      Abstract: 'Analysis of digital technologies in pandemic surveillance and control.',
      Field: 'Digital Health',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-54',
      Name: 'Public health communication in an age of social media',
      Authors: 'Merchant, RM & Lurie, N',
      Publication: 'JAMA',
      Year: '2020',
      Volume: '323',
      Issue: '21',
      Pages: '2151-2152',
      Type: 'Viewpoint',
      Keywords: 'social media, public health communication, digital platforms',
      Abstract: 'Strategies for effective public health communication via social media.',
      Field: 'Health Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-55',
      Name: 'Communicating uncertainty during public health emergency events',
      Authors: 'Ratzan, SC, et al.',
      Publication: 'Journal of Health Communication',
      Year: '2020',
      Volume: '25',
      Issue: '10',
      Pages: '763-769',
      Type: 'Editorial',
      Keywords: 'uncertainty communication, public health emergencies, trust, messaging',
      Abstract: 'Framework for communicating uncertainty during health emergencies.',
      Field: 'Health Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-56',
      Name: 'National Public Warning System',
      Authors: 'FEMA',
      Publication: 'Federal Emergency Management Agency',
      Year: '2023',
      Type: 'System Overview',
      Keywords: 'emergency alerts, public warning, communication infrastructure',
      Abstract: 'Overview of national systems for emergency public communication.',
      Field: 'Emergency Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-57',
      Name: 'The science of science communication III',
      Authors: 'National Academies of Sciences, Engineering, and Medicine',
      Publication: 'National Academies Press',
      Year: '2017',
      Type: 'Proceedings',
      Keywords: 'science communication, public understanding, evidence-based communication',
      Abstract: 'Evidence-based approaches to effective science communication.',
      Field: 'Science Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-58',
      Name: 'Building trust in COVID-19 vaccines and beyond',
      Authors: 'Larson, HJ',
      Publication: 'Health Affairs',
      Year: '2020',
      Volume: '39',
      Issue: '12',
      Pages: '2056-2060',
      Type: 'Perspective',
      Keywords: 'vaccine confidence, trust building, health communication, COVID-19',
      Abstract: 'Strategies for building public trust in vaccines and health interventions.',
      Field: 'Health Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-59',
      Name: 'Digital contact tracing for pandemic response',
      Authors: 'Ferretti, L, et al.',
      Publication: 'Science',
      Year: '2020',
      Volume: '368',
      Issue: '6491',
      Pages: 'eabb6936',
      Type: 'Research Article',
      Keywords: 'contact tracing, digital health, pandemic response, privacy',
      Abstract: 'Analysis of digital contact tracing effectiveness and implementation.',
      Field: 'Digital Health',
      Dimension: 'Information Infrastructure & Communication'
    },
    {
      id: 'bib-60',
      Name: 'Effective health risk communication about pandemic influenza',
      Authors: 'Vaughan, E & Tinker, T',
      Publication: 'American Journal of Public Health',
      Year: '2009',
      Volume: '99',
      Issue: 'S2',
      Pages: 'S324-S332',
      Type: 'Research Article',
      Keywords: 'risk communication, pandemic influenza, vulnerable populations, messaging',
      Abstract: 'Strategies for effective pandemic risk communication to diverse populations.',
      Field: 'Risk Communication',
      Dimension: 'Information Infrastructure & Communication'
    },
    // Dimension 7: Scientific Knowledge & Innovation Systems
    {
      id: 'bib-61',
      Name: 'The proximal origin of SARS-CoV-2',
      Authors: 'Andersen, KG, et al.',
      Publication: 'Nature Medicine',
      Year: '2020',
      Volume: '26',
      Issue: '4',
      Pages: '450-452',
      Type: 'Correspondence',
      Keywords: 'SARS-CoV-2, viral evolution, genomics, pandemic origins',
      Abstract: 'Analysis of SARS-CoV-2 genomic features and evolutionary origins.',
      Field: 'Virology',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-62',
      Name: 'A global initiative on sharing all influenza data',
      Authors: 'GISAID',
      Publication: 'Global Initiative on Sharing All Influenza Data',
      Year: '2024',
      Type: 'Database',
      Keywords: 'genomic surveillance, data sharing, influenza, SARS-CoV-2',
      Abstract: 'Global platform for sharing genomic data on influenza and coronaviruses.',
      Field: 'Genomic Epidemiology',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-63',
      Name: 'COVAX: ensuring global equitable access to COVID-19 vaccines',
      Authors: 'Berkley, S',
      Publication: 'The Lancet',
      Year: '2021',
      Volume: '397',
      Issue: '10278',
      Pages: '1043-1044',
      Type: 'Comment',
      Keywords: 'COVAX, vaccine equity, global health, pandemic response',
      Abstract: 'Overview of COVAX initiative for equitable vaccine distribution.',
      Field: 'Global Health',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-64',
      Name: 'Rapid development of COVID-19 vaccines',
      Authors: 'Krammer, F',
      Publication: 'Science',
      Year: '2020',
      Volume: '370',
      Issue: '6520',
      Pages: '912-913',
      Type: 'Perspective',
      Keywords: 'vaccine development, COVID-19, mRNA vaccines, innovation',
      Abstract: 'Analysis of accelerated COVID-19 vaccine development processes.',
      Field: 'Vaccinology',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-65',
      Name: 'Operation Warp Speed: implications for global vaccine security',
      Authors: 'Slaoui, M & Hepburn, M',
      Publication: 'The Lancet Global Health',
      Year: '2020',
      Volume: '8',
      Issue: '11',
      Pages: 'e1468-e1470',
      Type: 'Viewpoint',
      Keywords: 'Operation Warp Speed, vaccine development, pandemic preparedness',
      Abstract: 'Lessons from Operation Warp Speed for future vaccine development.',
      Field: 'Vaccine Policy',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-66',
      Name: 'The Coalition for Epidemic Preparedness Innovations',
      Authors: 'CEPI',
      Publication: 'Coalition for Epidemic Preparedness Innovations',
      Year: '2024',
      Type: 'Organization Overview',
      Keywords: 'epidemic preparedness, vaccine development, innovation, R&D',
      Abstract: 'CEPI's role in accelerating vaccine development for epidemic threats.',
      Field: 'Vaccine Innovation',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-67',
      Name: 'Pandemic preparedness and the road to international health regulations',
      Authors: 'Gostin, LO & Katz, R',
      Publication: 'JAMA',
      Year: '2016',
      Volume: '316',
      Issue: '14',
      Pages: '1441-1442',
      Type: 'Viewpoint',
      Keywords: 'International Health Regulations, global health law, pandemic preparedness',
      Abstract: 'Evolution and implementation of International Health Regulations.',
      Field: 'Global Health Law',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-68',
      Name: 'Drug repurposing for COVID-19',
      Authors: 'Pushpakom, S, et al.',
      Publication: 'Nature Reviews Drug Discovery',
      Year: '2020',
      Volume: '19',
      Issue: '6',
      Pages: '408-409',
      Type: 'News',
      Keywords: 'drug repurposing, COVID-19, therapeutics, innovation',
      Abstract: 'Strategies and progress in repurposing existing drugs for COVID-19.',
      Field: 'Drug Discovery',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-69',
      Name: 'Global research collaboration for infectious disease preparedness',
      Authors: 'GloPID-R',
      Publication: 'Global Research Collaboration for Infectious Disease Preparedness',
      Year: '2024',
      Type: 'Network Overview',
      Keywords: 'research collaboration, infectious disease, preparedness, funding',
      Abstract: 'Global network for coordinating research funding during outbreaks.',
      Field: 'Research Coordination',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-70',
      Name: 'Diagnostics for COVID-19: moving from pandemic response to control',
      Authors: 'Peeling, RW, et al.',
      Publication: 'The Lancet',
      Year: '2022',
      Volume: '399',
      Issue: '10326',
      Pages: '757-768',
      Type: 'Review',
      Keywords: 'diagnostics, COVID-19, testing strategies, innovation',
      Abstract: 'Evolution of diagnostic approaches for COVID-19 pandemic control.',
      Field: 'Diagnostic Innovation',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    // Additional Pandemic-Focused References
    {
      id: 'bib-71',
      Name: 'Global Pandemic Preparedness Summit Report',
      Authors: 'WHO & World Bank',
      Publication: 'Joint Publication',
      Year: '2023',
      Type: 'Summit Report',
      Keywords: 'pandemic preparedness, global cooperation, financing, governance',
      Abstract: 'Key outcomes and commitments from global pandemic preparedness summit.',
      Field: 'Global Health Security',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-72',
      Name: 'The Independent Panel for Pandemic Preparedness and Response',
      Authors: 'Clark, H & Sirleaf, EJ',
      Publication: 'The Lancet',
      Year: '2021',
      Volume: '398',
      Issue: '10296',
      Pages: '101-103',
      Type: 'Panel Report',
      Keywords: 'pandemic response, global governance, WHO reform, preparedness',
      Abstract: 'Independent panel recommendations for pandemic preparedness reform.',
      Field: 'Global Health Governance',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-73',
      Name: 'One Health approach to emerging infectious diseases',
      Authors: 'Mackenzie, JS & Jeggo, M',
      Publication: 'Microbiology Spectrum',
      Year: '2019',
      Volume: '7',
      Issue: '4',
      Type: 'Review',
      Keywords: 'One Health, emerging infectious diseases, zoonoses, surveillance',
      Abstract: 'Implementation of One Health approaches for disease emergence.',
      Field: 'One Health',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-74',
      Name: 'Pandemic bonds: designed to fail in Ebola',
      Authors: 'Brim, B & Wenham, C',
      Publication: 'BMJ Global Health',
      Year: '2019',
      Volume: '4',
      Pages: 'e001693',
      Type: 'Analysis',
      Keywords: 'pandemic financing, World Bank, Ebola, catastrophe bonds',
      Abstract: 'Critical analysis of pandemic bond mechanisms and effectiveness.',
      Field: 'Health Financing',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-75',
      Name: 'The Global Virome Project',
      Authors: 'Carroll, D, et al.',
      Publication: 'Science',
      Year: '2018',
      Volume: '359',
      Issue: '6378',
      Pages: '872-874',
      Type: 'Policy Forum',
      Keywords: 'viral discovery, pandemic prevention, surveillance, One Health',
      Abstract: 'Proposal for comprehensive viral discovery to prevent pandemics.',
      Field: 'Viral Surveillance',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-76',
      Name: 'After Ebola in West Africa',
      Authors: 'National Academy of Medicine',
      Publication: 'NAM',
      Year: '2016',
      Type: 'Report',
      Keywords: 'Ebola, West Africa, health systems, lessons learned',
      Abstract: 'Lessons from Ebola outbreak for health system strengthening.',
      Field: 'Health Systems',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-77',
      Name: 'The economic and social burden of the 2014 Ebola outbreak',
      Authors: 'Huber, C, et al.',
      Publication: 'Journal of Infectious Diseases',
      Year: '2018',
      Volume: '218',
      Issue: 'S5',
      Pages: 'S698-S704',
      Type: 'Research Article',
      Keywords: 'Ebola, economic impact, social burden, West Africa',
      Abstract: 'Quantification of economic and social impacts of 2014 Ebola outbreak.',
      Field: 'Health Economics',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-78',
      Name: 'Framework for a Public Health Emergency Operations Centre',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2015',
      Type: 'Framework',
      Keywords: 'emergency operations, public health, coordination, response',
      Abstract: 'WHO framework for establishing public health emergency operations centres.',
      Field: 'Emergency Management',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-79',
      Name: 'Disease X: accelerating the development of medical countermeasures',
      Authors: 'Simpson, S, et al.',
      Publication: 'The Lancet Infectious Diseases',
      Year: '2020',
      Volume: '20',
      Issue: '5',
      Pages: 'e108-e115',
      Type: 'Review',
      Keywords: 'Disease X, medical countermeasures, R&D, pandemic preparedness',
      Abstract: 'Strategies for developing countermeasures against unknown pathogens.',
      Field: 'Medical Countermeasures',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-80',
      Name: 'Global health security: the wider lessons from the west African Ebola virus disease epidemic',
      Authors: 'Moon, S, et al.',
      Publication: 'The Lancet',
      Year: '2015',
      Volume: '385',
      Issue: '9980',
      Pages: '1884-1901',
      Type: 'Series',
      Keywords: 'global health security, Ebola, health systems, governance',
      Abstract: 'Comprehensive lessons from Ebola for global health security.',
      Field: 'Global Health Security',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-81',
      Name: 'Strengthening global health security by embedding the International Health Regulations requirements',
      Authors: 'Kluge, H, et al.',
      Publication: 'BMJ',
      Year: '2018',
      Volume: '361',
      Pages: 'k2269',
      Type: 'Analysis',
      Keywords: 'International Health Regulations, health security, implementation',
      Abstract: 'Strategies for implementing IHR requirements in health systems.',
      Field: 'Global Health Security',
      Dimension: 'Governance Coordination & Community Leadership'
    },
    {
      id: 'bib-82',
      Name: '100 Days Mission to Respond to Future Pandemic Threats',
      Authors: 'G7 Partnership',
      Publication: 'G7',
      Year: '2021',
      Type: 'Report',
      Keywords: '100 days, vaccine development, pandemic response, G7',
      Abstract: 'G7 commitment to develop vaccines within 100 days of pandemic threat.',
      Field: 'Vaccine Development',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-83',
      Name: 'Pandemic influenza preparedness in the WHO European region',
      Authors: 'WHO Europe',
      Publication: 'WHO Regional Office for Europe',
      Year: '2023',
      Type: 'Regional Report',
      Keywords: 'pandemic influenza, preparedness, Europe, regional coordination',
      Abstract: 'Regional assessment of pandemic influenza preparedness in Europe.',
      Field: 'Regional Health Security',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-84',
      Name: 'The Global Fund to Fight AIDS, Tuberculosis and Malaria',
      Authors: 'Global Fund',
      Publication: 'The Global Fund',
      Year: '2024',
      Type: 'Organization Overview',
      Keywords: 'global health financing, pandemic response, health systems',
      Abstract: 'Global Fund's role in pandemic preparedness and health system strengthening.',
      Field: 'Health Financing',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-85',
      Name: 'Antimicrobial resistance and pandemic preparedness',
      Authors: 'Laxminarayan, R, et al.',
      Publication: 'The Lancet',
      Year: '2023',
      Volume: '401',
      Issue: '10382',
      Pages: '1066-1068',
      Type: 'Comment',
      Keywords: 'antimicrobial resistance, pandemic preparedness, One Health',
      Abstract: 'Links between antimicrobial resistance and pandemic preparedness.',
      Field: 'Antimicrobial Resistance',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-86',
      Name: 'Health emergency and disaster risk management framework',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2019',
      Type: 'Framework',
      Keywords: 'disaster risk management, health emergencies, all-hazards approach',
      Abstract: 'WHO framework for health emergency and disaster risk management.',
      Field: 'Disaster Risk Management',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-87',
      Name: 'Universal health coverage for pandemic preparedness',
      Authors: 'Wenham, C, et al.',
      Publication: 'BMJ',
      Year: '2019',
      Volume: '365',
      Pages: 'l2295',
      Type: 'Analysis',
      Keywords: 'universal health coverage, pandemic preparedness, health systems',
      Abstract: 'Role of universal health coverage in pandemic preparedness.',
      Field: 'Health Systems',
      Dimension: 'Healthcare System Capacity & Integration'
    },
    {
      id: 'bib-88',
      Name: 'The R&D Blueprint for action to prevent epidemics',
      Authors: 'WHO',
      Publication: 'World Health Organization',
      Year: '2023',
      Type: 'Blueprint',
      Keywords: 'R&D, epidemic prevention, priority diseases, innovation',
      Abstract: 'WHO R&D Blueprint for accelerating development of medical countermeasures.',
      Field: 'Research & Development',
      Dimension: 'Scientific Knowledge & Innovation Systems'
    },
    {
      id: 'bib-89',
      Name: 'Financing pandemic preparedness at a national level',
      Authors: 'World Bank',
      Publication: 'World Bank Group',
      Year: '2017',
      Type: 'Report',
      Keywords: 'pandemic financing, national preparedness, investment case',
      Abstract: 'Framework for financing national pandemic preparedness efforts.',
      Field: 'Health Financing',
      Dimension: 'Economic Stability & Crisis Protection'
    },
    {
      id: 'bib-90',
      Name: 'The Global Health Security Index',
      Authors: 'Nuclear Threat Initiative, Johns Hopkins Center for Health Security',
      Publication: 'GHS Index',
      Year: '2021',
      Type: 'Index Report',
      Keywords: 'health security, preparedness assessment, global index, capacity',
      Abstract: 'Comprehensive assessment of global health security capabilities.',
      Field: 'Health Security Assessment',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-91',
      Name: 'Sendai Framework for Disaster Risk Reduction 2015-2030',
      Authors: 'UNDRR',
      Publication: 'United Nations Office for Disaster Risk Reduction',
      Year: '2015',
      Type: 'Framework',
      Keywords: 'disaster risk reduction, Sendai Framework, resilience, health',
      Abstract: 'Global framework for disaster risk reduction including health emergencies.',
      Field: 'Disaster Risk Reduction',
      Dimension: 'Multiple'
    },
    {
      id: 'bib-92',
      Name: 'Building resilient health systems: lessons from island nations',
      Authors: 'Aumua, A, et al.',
      Publication: 'The Lancet Regional Health - Western Pacific',
      Year: '2023',
      Volume: '31',
      Pages: '100641',
      Type: 'Series',
      Keywords: 'health system resilience, island nations, climate change, pandemics',
      Abstract: 'Lessons from island nations on building resilient health systems.',
      Field: 'Health Systems',
      Dimension: 'Healthcare System Capacity & Integration'
    }
  ];
}

export async function GET() {
  try {
    console.log('📚 Loading comprehensive bibliography...');
    
    // Always use the comprehensive bibliography data
    const bibliographyData = getFallbackBibliography();
    
    console.log(`✅ Loaded ${bibliographyData.length} bibliography entries`);
    
    return NextResponse.json({ 
      papers: bibliographyData,
      source: 'comprehensive',
      total: bibliographyData.length
    });
  } catch (error) {
    console.error('🔴 Error loading bibliography data:', error);
    
    // Fallback to empty array if something goes wrong
    return NextResponse.json({ 
      papers: [],
      source: 'error',
      error: error.message 
    });
  }
}